import logging
from typing import Dict, Any

from api.gcs_utils import download_from_gcs, upload_to_gcs

logger = logging.getLogger("vectosports-review-consumer")

OPTIMIZATION_INSTRUCTION = """You are a Senior Technical Editor for Biomechanics Reports.
Your task is to POLISH and CORRECT an existing "Relatório de Evolução Biomecânica".

**GOAL:**
Ensure the text is professional, scientifically accurate, and free of specific errors like wrong timestamps. Do NOT rewrite the core analysis logic - just improve how it is presented.

**CRITICAL EDITING RULES:**

1. **REMOVE TIMESTAMPS:** 
   - If the report mentions specific timestamps (e.g., "at 0:12", "no minuto 1:05"), REMOVE THEM instantly. 
   - Replace with qualitative descriptions like "na fase de entrada", "durante a recuperação", or "no vídeo anterior".
   - REASON: Timestamps are often inaccurate generated by AI.

2. **PRESERVE ORIGINAL ANALYSIS:**
   - Do NOT add new diagnoses (like EVF, Head Position) if they are not in the input text.
   - Do NOT change the meaning of the observations.
   - You are an EDITOR, not the analyst. Trust the input observations.

3. **TONE & STYLE:**
   - Maintain a **SOBER, SCIENTIFIC** tone.
   - Remove clichés like "A cabeça guia o corpo".
   - Ensure specific data points (Names, Dates) remain untouched.

4. **STRUCTURE:**
   - Keep the exact structure of the input report.
   - Ensure the output strictly follows the markdown structure provided in the input.

**INPUT:**
The existing markdown content of a report.

**OUTPUT:**
The polished markdown report.
"""

def handle_review_message(payload: Dict[str, Any]):
    """
    RabbitMQ callback for report review/optimization jobs.
    Payload expected:
    {
        "gcsPath": "gs://bucket/path/to/report.md"
    }
    """
    logger.info(f"📩 Received review job: {payload}")
    
    gcs_path = payload.get('gcsPath')
    if not gcs_path:
        logger.error("❌ No gcsPath provided in payload")
        return

    try:
        # Download the report from GCS
        logger.info(f"📥 Downloading report from {gcs_path}")
        
        from api.gcs_utils import get_gcs_client, parse_gcs_uri
        
        client = get_gcs_client()
        bucket_name, blob_name = parse_gcs_uri(gcs_path)
        bucket = client.bucket(bucket_name)
        blob = bucket.blob(blob_name)
        
        # Download as string
        report_content = blob.download_as_text()
        
        if not report_content:
            logger.error(f"❌ Failed to download report from {gcs_path}")
            return
        
        logger.info(f"📄 Downloaded {len(report_content)} characters")
        
        # Optimize the report using Gemini
        logger.info(f"🔧 Optimizing report...")
        from google import genai
        from google.genai import types
        import os
        
        api_key = os.environ.get("GOOGLE_API_KEY")
        if not api_key:
            logger.error("❌ GOOGLE_API_KEY not set")
            return
        
        genai_client = genai.Client(api_key=api_key)
        
        # Import the enhanced OPTIMIZATION_INSTRUCTION from the script
        from ai_agents.vectosports.scripts.optimize_reports import OPTIMIZATION_INSTRUCTION as ENHANCED_INSTRUCTION
        
        response = genai_client.models.generate_content(
            model='gemini-3-flash-preview',
            config=types.GenerateContentConfig(
                temperature=0.5,
                system_instruction=ENHANCED_INSTRUCTION
            ),
            contents=[report_content]
        )
        
        optimized_content = response.text
        
        # Extract content if wrapped in tags
        import re
        match = re.search(r'<!--FINAL_REPORT_STRUCTURE_START-->(.*?)<!--FINAL_REPORT_STRUCTURE_END-->', optimized_content, re.DOTALL)
        if match:
            optimized_content = match.group(1).strip()
            optimized_content = f"<!--FINAL_REPORT_STRUCTURE_START-->\n{optimized_content}\n<!--FINAL_REPORT_STRUCTURE_END-->"
        
        # Upload the optimized report back to GCS
        logger.info(f"📤 Uploading optimized report to {gcs_path}")
        blob.upload_from_string(optimized_content, content_type='text/markdown')
        
        logger.info(f"✅ Report optimization completed for {gcs_path}")

    except Exception as e:
        logger.error(f"❌ Error in review consumer: {e}", exc_info=True)
        raise
