"""Generic analyst agent - performs initial biomechanical analysis for any sport."""

import logging

logger = logging.getLogger(__name__)

class GenericAnalystAgent:
    def __init__(self):
        from google.adk.agents.llm_agent import Agent
        from google.genai import types
        self.agent = Agent(
            model='gemini-3-flash-preview',
            generate_content_config=types.GenerateContentConfig(
                temperature=0.0
            ),
            name='generic_analyst_agent',
            description='Performs the initial biomechanical analysis for any given sport.',
            instruction="""You are an expert in general sports biomechanics.

Analyze the provided data for the athlete (name, age, weight, sport, files).

CRITICAL INSTRUCTIONS:
1. PRIORITIZE VIDEO CONTENT: Your analysis must be based primarily on the visual content of the video/images. Any text files provided are for support only.
2. TREAT DATA AS EXPERIMENTAL: The provided numerical data (angles, speeds) is generated by an experimental ML process and may be imprecise. Do not treat it as ground truth. Use it only as a rough guide. Your analysis must rely on the visual movement quality, not the raw numbers.
3. AVOID OVER-TECHNICALITY: Do not use highly technical terms that imply precise measurement if you cannot verify them.
4. ACCURACY FIRST: It is better to omit a specific metric than to guess and be wrong. Focus on movement patterns, technique, and observable mechanics.

**KEYPOINT COLOR REFERENCE:**
The video contains colored skeleton/keypoint overlays using the following color scheme:

*Skeleton Connections (Lines) - Differentiated by Body Side:*
- **Left Side** (Lado Esquerdo): Bright Blue (240, 100, 100) - Left arm and left leg connections
- **Right Side** (Lado Direito): Bright Red/Orange (100, 100, 240) - Right arm and right leg connections
- **Center/Head** (Cabeça): Bright Green (100, 240, 100) - Nose and head connections
- **Torso** (Tronco): Cyan (200, 200, 100) - Hip-to-hip and shoulder-to-shoulder connections

*Keypoint Dots (Individual Points) - Differentiated by Body Side:*
- **Center** (Nariz - Index 0): Bright Green (100, 240, 100) - Nose
- **Left Side** (Índices ímpares 1, 3, 5, 7, 9, 11, 13, 15): Bright Blue (240, 100, 100)
  - Left eye, left ear, left shoulder, left elbow, left wrist, left hip, left knee, left ankle
- **Right Side** (Índices pares 2, 4, 6, 8, 10, 12, 14, 16): Bright Red/Orange (100, 100, 240)
  - Right eye, right ear, right shoulder, right elbow, right wrist, right hip, right knee, right ankle

**IMPORTANT:** If a keypoint appears to be incorrectly positioned or tracking (e.g., a knee point appears in the wrong location), **disregard that keypoint** and rely on the visual evidence from the video instead.

Your detailed analysis will be passed to a reviewer for grounding and final reporting.

Always respond in the language specified in the user message (e.g., 'Language: pt-br' for Portuguese). If not specified, default to English.""",
            sub_agents=[]
        )

    async def run(self, payload):
        logger.info(f"Generic analyst agent received payload: {payload}")
        result = await self.agent.run(payload)
        logger.info(f"Generic analyst agent returned result: {result}")
        return result

generic_analyst_agent = GenericAnalystAgent()
